### ISSUE TITLE
Mutpy last version is broken

### ISSUE THREAD

**Issue by dunossauro** [mutpy/mutpy#43]
```
(...)lib/python3.7/site-packages/mutpy/utils.py
", line 71, in is_package
    return module.__file__.endswith('__init__.py')
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by phihos** [comment]
Can you try it with the new v0.6.0?

**Comment by dunossauro** [comment]
Yes, I can. In a few hours, I report here.

Thanks for your attention.

**Comment by dunossauro** [comment]
@phihos, I really appreciate the lib, if you need help to execute other tests, or something else, I'd love to help.

**Comment by phihos** [comment]
Thank you :-) Anything from reporting bugs to writing tests or new test runners is appreciated. For example it is possible since the latest release to run tests with something else than unittest. I added experimental pytest support, but of course some runners like Django or Nosetests are still missing. But these are just some examples. Find the thing that annoys you the most and attempt to fix it ;-)

**Comment by dunossauro** [comment]
@phihos Nice, I'll try run more tests :)

----------------------------

Now, about the error with `__init__.py`

```
$ mut.py -t app --runner pytest -u tests.test_aor
[*] Start mutation process:
   - targets: app
   - tests: tests.test_aor
[*] 1 tests passed:
   - tests.test_aor [0.10617 s]
[*] Start mutants generation and execution:
Traceback (most recent call last):

  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/bin/mut.py", line 7, in <module>
    commandline.main(sys.argv)
  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/lib/python3.7/site-packages/mutpy/commandline.py", line 10, in ma
in
    run_mutpy(parser)
  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/lib/python3.7/site-packages/mutpy/commandline.py", line 62, in ru
n_mutpy
    mutation_controller.run()
  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/lib/python3.7/site-packages/mutpy/controller.py", line 66, in run
    self.run_mutation_process()
  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/lib/python3.7/site-packages/mutpy/controller.py", line 84, in run
_mutation_process
    for target_module, to_mutate in self.target_loader.load([module for module, *_ in test_modules]):
  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/lib/python3.7/site-packages/mutpy/utils.py", line 60, in load
    if module not in without_modules and not (exclude_c_extensions and self._is_c_extension(module)):
  File "/home/eduardo.mendes/.local/share/virtualenvs/mutpy_test-Nh1QybqH/lib/python3.7/site-packages/mutpy/utils.py", line 187, in _is_c_e
xtension
    module_filename = inspect.getfile(module)
  File "/usr/local/lib/python3.7/inspect.py", line 647, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'app' (namespace)> is a built-in module
```

When I create __init__ file works correctly 

```
$ mut.py -t app --runner pytest -u tests.test_aor
[*] Start mutation process:
   - targets: app
   - tests: tests.test_aor
[*] 1 tests passed:
   - tests.test_aor [0.10040 s]
[*] Start mutants generation and execution:
   - [#   1] AOR app.app: [0.11951 s] survived
[*] Mutation score [0.23912 s]: 0.0%
   - all: 1
   - killed: 0 (0.0%)
   - survived: 1 (100.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
```

Python version: Python 3.7.0
Mutpy version: 0.6.0

**Comment by dunossauro** [comment]
WOW, and absolutely nice. Works with Pytest
